__version__ = "1.1.2"
__author__ = "Alan Elkner"
__copyright__ = "Copyright 2018, Alan Elkner"
__maintainer__ = "Alan Elkner"
__email__ = "aelkner@gmail.com"
__license__ = "GNU GENERAL PUBLIC LICENSE version 3"
